# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_FmvSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.video_dir_widget = gui.QgsFileWidget(Settings)
        self.video_dir_widget.setStorageMode(gui.QgsFileWidget.GetDirectory)
        self.video_dir_widget.setOptions(QtWidgets.QFileDialog.ShowDirsOnly)
        self.video_dir_widget.setObjectName("video_dir_widget")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.video_dir_widget)
        self.label = QtWidgets.QLabel(Settings)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(Settings)
        self.video_dir_widget.fileChanged['QString'].connect(Settings.on_dir_change)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.label.setText(_translate("Settings", "Video directory"))
from qgis import gui
