# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_FmvOpenDatabase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenDatabase(object):
    def setupUi(self, OpenDatabase):
        OpenDatabase.setObjectName("OpenDatabase")
        OpenDatabase.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(OpenDatabase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(OpenDatabase)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.db_list = QtWidgets.QListWidget(self.groupBox)
        self.db_list.setObjectName("db_list")
        self.verticalLayout_2.addWidget(self.db_list)
        self.db_connect = QtWidgets.QPushButton(self.groupBox)
        self.db_connect.setObjectName("db_connect")
        self.verticalLayout_2.addWidget(self.db_connect)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(OpenDatabase)
        self.db_connect.clicked.connect(OpenDatabase.load_layer)
        QtCore.QMetaObject.connectSlotsByName(OpenDatabase)

    def retranslateUi(self, OpenDatabase):
        _translate = QtCore.QCoreApplication.translate
        OpenDatabase.setWindowTitle(_translate("OpenDatabase", "Open Database"))
        self.groupBox.setTitle(_translate("OpenDatabase", "Datenbankverbindungen"))
        self.db_connect.setText(_translate("OpenDatabase", "Verbinden"))
