# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_FmvSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Settings)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.video_dir_widget = gui.QgsFileWidget(Settings)
        self.video_dir_widget.setStorageMode(gui.QgsFileWidget.GetDirectory)
        self.video_dir_widget.setOptions(QtWidgets.QFileDialog.ShowDirsOnly)
        self.video_dir_widget.setObjectName("video_dir_widget")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.video_dir_widget)
        self.db_combobox = QtWidgets.QComboBox(Settings)
        self.db_combobox.setObjectName("db_combobox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.db_combobox)
        self.label_2 = QtWidgets.QLabel(Settings)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.db_reload_btn = QtWidgets.QPushButton(Settings)
        self.db_reload_btn.setObjectName("db_reload_btn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.db_reload_btn)
        self.db_save_btn = QtWidgets.QPushButton(Settings)
        self.db_save_btn.setObjectName("db_save_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.db_save_btn)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(Settings)
        self.video_dir_widget.fileChanged['QString'].connect(Settings.on_dir_change)
        self.db_save_btn.clicked['bool'].connect(Settings.save_db)
        self.db_reload_btn.clicked['bool'].connect(Settings.populate_db)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.label.setText(_translate("Settings", "Video directory"))
        self.label_2.setText(_translate("Settings", "Database"))
        self.db_reload_btn.setText(_translate("Settings", "reload Database connections"))
        self.db_save_btn.setText(_translate("Settings", "test and save connection"))
from qgis import gui
